//
// Created by liliangk on 2017/8/21.
//
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_liliangk_jnitest2_myJNI */

#ifndef _Included_com_example_liliangk_jnitest2_myJNI
#define _Included_com_example_liliangk_jnitest2_myJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_liliangk_jnitest2_myJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_liliangk_jnitest2_myJNI_sayHello
  (JNIEnv * env, jclass jobj)
  {
  return (*env)->NewStringUTF(env,"hello word!!");

  }

#ifdef __cplusplus
}
#endif
#endif

